### ISSUE TITLE
CSI driver bound CSIStorageCapacity to node

### ISSUE THREAD

**Issue by AdamNuclear** [scylladb/k8s-local-volume-provisioner#9]
We are having issues with left overs of 
```
apiVersion: storage.k8s.io/v1beta1
capacity: 857372994Ki
kind: CSIStorageCapacity
metadata:
  creationTimestamp: '2023-05-02T09:40:14Z'
  generateName: csisc-
  labels:
    csi.storage.k8s.io/drivername: local.csi.scylladb.com
    csi.storage.k8s.io/managed-by: external-provisioner-
  name: csisc-52vb8
```

They should be bounded to node and deleted when node is deleted
